# Do we want to send players a message when they are reconnected to a server?
message-on-reconnect: true
reconnect-message:
  - "&7You were reconnected to &f%server%&7."

# Do we want to send a message when their previous server isn't available?
not-available: true
not-available-message:
  - "&7Unable to reconnect you to your last server."

# For each server, do want to make sure that user has permissions to reconnect to that server
# permission: velocity.reconnect.#servername
per-server-permissions: false

# List any servers that you do not want people to reconnect to.
blacklist:
  - servername

# If set to true, prevents connection to fallback servers.
# Server should not be on the blacklist.
prevent-fallback: false
prevent-fallback-message: ''

###################### STORAGE
# Default: "yaml"
# Options:
#   - "mysql" <- Remote or Local SQL database
#   - "yaml" <- Local .yml file
#   - "sqlite" <- Local SQL database
storage:
  method: "yaml"
  # The below is only needed if you are using MySQL
  data:
    address: localhost
    database: reconnect.db
    username: root
    password: ''
